site_name: lkww
site_description: 立刻旺旺
site_author: vesaa


theme:
  name: material
  feature:
    tabs: true
  include_sidebar: false
  palette:
    - scheme: default
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.path
    - navigation.prune
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.code.copy

plugins:
  - search

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark

nav:
  - 首页: 'index.md'